CREATE OR REPLACE PACKAGE RRHH."PKG_CATALOGOS"
AS
    PROCEDURE PROC_GET_DEPARTAMENTO (p_cur_dataset OUT SYS_REFCURSOR,p_msj OUT VARCHAR2 );
    PROCEDURE PROC_GET_MUNICIPIO (P_ID_DEPARTAMENTO IN RRHH.RH_MUNICIPIO.DEPARTAMENTO%TYPE, P_CUR_DATASET OUT SYS_REFCURSOR,P_MSJ OUT VARCHAR2);
    PROCEDURE PROC_GET_DEP_AREA (P_CUR_DATASET OUT SYS_REFCURSOR,P_MSJ OUT VARCHAR2);
END "PKG_CATALOGOS";
/