ALTER TABLE RRHH.RH_MUNICIPIO
 DROP PRIMARY KEY CASCADE;

DROP TABLE RRHH.RH_MUNICIPIO CASCADE CONSTRAINTS;

CREATE TABLE RRHH.RH_MUNICIPIO
(
  PAIS                         NUMBER(3)        NOT NULL,
  DEPARTAMENTO                 NUMBER(3)        NOT NULL,
  MUNICIPIO                    NUMBER(3)        NOT NULL,
  NOMBRE_MUNICIPIO             VARCHAR2(30 BYTE) NOT NULL,
  ABREVIATURA_MUNICIPIO        VARCHAR2(5 BYTE) NOT NULL,
  FECHA_FERIA_LOCAL            DATE             DEFAULT sysdate               NOT NULL,
  FERIA_LOCAL_FIJO             CHAR(1 BYTE)     DEFAULT 'S'                   NOT NULL,
  USUARIO_DEFINIO_FERIA_LOCAL  VARCHAR2(40 BYTE) DEFAULT USER NOT NULL,
  FECHA_ULTIMA_MODIFICACION    DATE             DEFAULT SYSDATE               NOT NULL,
  OBSERVACIONES                VARCHAR2(128 BYTE)
)
TABLESPACE TS_RRHH2021
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

COMMENT ON TABLE RRHH.RH_MUNICIPIO IS 'Descripcion general de los municipios departamentales.';

COMMENT ON COLUMN RRHH.RH_MUNICIPIO.PAIS IS 'Codigo del pais';

COMMENT ON COLUMN RRHH.RH_MUNICIPIO.DEPARTAMENTO IS 'Codigo del departamento o provincia';

COMMENT ON COLUMN RRHH.RH_MUNICIPIO.MUNICIPIO IS 'Codigo del municipio';

COMMENT ON COLUMN RRHH.RH_MUNICIPIO.NOMBRE_MUNICIPIO IS 'Nombre del municipio';

COMMENT ON COLUMN RRHH.RH_MUNICIPIO.ABREVIATURA_MUNICIPIO IS 'Abreviatura del municipio departamenta';



CREATE INDEX RRHH.XIF5MUNICIPIO ON RRHH.RH_MUNICIPIO
(DEPARTAMENTO, PAIS)
LOGGING
TABLESPACE TS_RRHH_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RRHH.XPKMUNICIPIO ON RRHH.RH_MUNICIPIO
(PAIS, DEPARTAMENTO, MUNICIPIO)
LOGGING
TABLESPACE TS_RRHH_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          40K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


ALTER TABLE RRHH.RH_MUNICIPIO ADD (
  CONSTRAINT CK_FERIA_LOCAL_FIJO
  CHECK (feria_local_fijo in ( 'S', 'N' ))
  ENABLE VALIDATE,
  CONSTRAINT XPKMUNICIPIO
  PRIMARY KEY
  (PAIS, DEPARTAMENTO, MUNICIPIO)
  USING INDEX RRHH.XPKMUNICIPIO
  ENABLE VALIDATE);

ALTER TABLE RRHH.RH_MUNICIPIO ADD (
  CONSTRAINT R_MUNICIPIO_DEPARTAMENTO 
  FOREIGN KEY (PAIS, DEPARTAMENTO) 
  REFERENCES RRHH.RH_DEPARTAMENTO (PAIS,DEPARTAMENTO)
  ENABLE VALIDATE);


GRANT SELECT ON RRHH.RH_MUNICIPIO TO SIDEP;

