ALTER TABLE RRHH.RH_TIPO_AREA
 DROP PRIMARY KEY CASCADE;

DROP TABLE RRHH.RH_TIPO_AREA CASCADE CONSTRAINTS;

CREATE TABLE RRHH.RH_TIPO_AREA
(
  ID_AREA      NUMBER(2)                        NOT NULL,
  NOMBRE_AREA  VARCHAR2(50 BYTE)                NOT NULL
)
TABLESPACE TS_RRHH2021
RESULT_CACHE (MODE DEFAULT)
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
ENABLE ROW MOVEMENT;

COMMENT ON TABLE RRHH.RH_TIPO_AREA IS 'CONTENDRA EL CATALOGO DE LAS CLASIFICACION DE LAS DEPENDENCIAS POR AREA 1=JURIS, 2=ADMITIVA, ETC.';

COMMENT ON COLUMN RRHH.RH_TIPO_AREA.ID_AREA IS 'IDENTIFICACION DEL CODIGO DE AREA';

COMMENT ON COLUMN RRHH.RH_TIPO_AREA.NOMBRE_AREA IS 'NOMBRE DESIGNADO AL REA';



CREATE INDEX RRHH.IDX_NOMREAREA ON RRHH.RH_TIPO_AREA
(NOMBRE_AREA)
LOGGING
TABLESPACE TS_RRHH_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX RRHH.PK_RH_TIPO_AREA ON RRHH.RH_TIPO_AREA
(ID_AREA)
LOGGING
TABLESPACE TS_RRHH_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE SYNONYM CLORTIZ.RH_TIPO_AREA FOR RRHH.RH_TIPO_AREA;


CREATE OR REPLACE PUBLIC SYNONYM RH_TIPO_AREA FOR RRHH.RH_TIPO_AREA;


ALTER TABLE RRHH.RH_TIPO_AREA ADD (
  CONSTRAINT PK_RH_TIPO_AREA
  PRIMARY KEY
  (ID_AREA)
  USING INDEX RRHH.PK_RH_TIPO_AREA
  ENABLE VALIDATE);

GRANT SELECT ON RRHH.RH_TIPO_AREA TO CONSULTA_RRHH_REST;

GRANT SELECT ON RRHH.RH_TIPO_AREA TO ROLE_REPORT_SERVICE;

GRANT INSERT, SELECT, UPDATE ON RRHH.RH_TIPO_AREA TO ROLE_RRHH;

GRANT SELECT ON RRHH.RH_TIPO_AREA TO SIDEP;

GRANT SELECT ON RRHH.RH_TIPO_AREA TO UCI;


